### ISSUE TITLE
Erreur start date

### ISSUE THREAD

**Issue by Robs68** [tthma/homebridge-linky-enedis-meter#12]
Bonjour,

J'ai un soucis lors du démarrage du plugins. 

`[1/6/2023, 12:52:49 PM] [Linky Meter] Query start = 2022-02-01 End = 2022-02-08
[1/6/2023, 12:52:50 PM] [Linky Meter] Error: Invalid request: The requested period cannot be anterior to the meter's last activation date
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/6/2023, 12:52:50 PM] [Linky Meter] Error: Invalid request: The requested period cannot be anterior to the meter's last activation date
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

Pourtant je rentre dans le fichier config un démarrage en avril 2022. 

Que dois-je faire ?

Je vous remercie,

Robs

**Comment by tthma** [comment]
Bonjour 

Est-ce que je pourrais avoir un visu sur votre fichier de config ?

**Comment by Robs68** [comment]
Merci pour votre retour rapide :) 

Voici mon fichier config de homebridge : 

`{
    "bridge": {
        "name": "Homebridge 22AE",
        "username": "xx:xx:xx:95:22:AE",
        "port": 51954,
        "pin": "xxx-xx-721",
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "name": "Linky Meter",
            "usagePointId": "2xxxxxxxxxxxxx",
            "accessToken": "98aPmoU3bxxxxxxxxxxxxxxIxxxN8k6b5FTw208Ic4a",
            "refreshToken": "O88xxxxxxxxxxxxxxxavODo4EPjrk7J6k8H0v",
            "firstDateRecord": "2023-01-06T13:00:00Z",
            "update_interval": 60000,
            "accessory": "EnergyMeter"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}`

**Comment by tthma** [comment]
Je vais check tout à l'heure et en plus j'ai une mise à jour à faire qui traîne depuis 20 ans sur mon pc.
Je l'ai pas faite par manque de temps.
Après si vous avez lancé le plugin hier et que la date de premier enregistrement c'était hier aussi c'est ça qu'il a pas dû apprécier.

Y aura toujours un jour de décalage entre la réception des données par enedis et le plugin.
Enedis ne fait pas de temps réel sur son api toujours la veille pour le lendemain. 

Donc le plugin a pas aimé je pense récupérer les données du jour pour le jour même (firstdaterecord doit être différent de la date du jour actuelle).
Antérieur à la date du jour mais si vos données commence le même jour il va falloir attendre au moins une journée du coup.

Là on est le 7 un petit reset dans ÈVE et ça devrait fonctionner à nouveau.

**Comment by Robs68** [comment]
La date semble figée sur : 
`[Linky Meter] Query start = 2022-02-01 End = 2022-02-08` Alors que je mets la date du jour ? 

Question ultra bête : quand vous dites reset dans EVE, vous faites quoi ?

**Comment by tthma** [comment]
![image](https://user-images.githubusercontent.com/113852575/211146501-d8088541-02d5-4bbc-9ca1-8f1ae9b6088d.png)

Réinitialiser les valeurs.

**Comment by tthma** [comment]
Réinitialiser les valeurs et après restart homebridge.

Normalement ça vas repartir sinon dites moi ça que ça fait

**Comment by Robs68** [comment]
Merci, j'avais jamais vu qu'il y avait cette possibilité dans EVE. 

Du coup, après reset et rebooté de homebridge je n'ai plus d'erreur. J'ai mis la date du jour donc je n'ai pour l'instant aucune donnée dispo. 

Je reviens vers vous si encore des soucis. 

Merci pour le débug avec moi :D 

Bonne journée

**Comment by tthma** [comment]
Je vais déployer une mise à jour là 
Un vieux truc qui traîne sur mon pc.

A voir à partir de demain si vous avez des nouvelles data qui arrivent.

Mais c'est vrai que c'est pas du temps réel mais bon la consommation de la veille c'est déjà pas mal

**Comment by Robs68** [comment]
Oui c'est clair ça suffit, merci beaucoup pour le plugins !

**Comment by tthma** [comment]
Ça a donné quoi aujourd'hui ?

**Comment by Robs68** [comment]
C'est bon ça marche 😀 

Merci bcp ! Super plug-ins
