### ISSUE TITLE
Problème config

### ISSUE THREAD

**Issue by Gabin85** [tthma/homebridge-linky-enedis-meter#13]
J'ai beau mettre des dates j'ai toujours ce message d'erreur, quelqu'un peut m'aider...
[1/23/2023, 8:36:01 PM] [Linky Meter] Error: Invalid request: The start date must be greater than the history deadline.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/23/2023, 8:36:01 PM] [Linky Meter] Error: Invalid request: The start date must be greater than the history deadline.
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by tthma** [comment]
Bonjour
Je crois que certains on déjà eu ce problème faut check dans les issues déjà clôturé.

Je peux avoir votre fichier config en attendant ? Je vais check la config.

Attention à cacher les données sensibles.

**Comment by Gabin85** [comment]
{
    "name": "Linky Meter",
    "usagePointId": "111111111111",
    "accessToken": "djieoirfeioieir",
    "refreshToken": "xxxxxduyezgfiugeziuyfgiuezbxxxxxxxxx",
    "firstDateRecord": "2020-02-07T20:34:00Z",
    "update_interval": 60000,
    "accessory": "EnergyMeter"
}

J'ai enlevé bien évidement les infos sensibles

**Comment by tthma** [comment]
Bonjour

Essayez en mettant moins d'un an de décalage sur la date.
Genre on est le 24/01/2023 mettre le 25/01/2022.

Si ça fonctionne je vois d'où ça viens je corrigerai

**Comment by Gabin85** [comment]
Bonjour, excuse moi pour la réponse tardive, j'ai essayé plein de date différentes, toujours une erreur.

**Comment by Gabin85** [comment]
Et Je suis banni maintenant, j'essaye de régénérer un token mais impossible, la page ENEDIS s'actualise à l'infini... j'ai essayé sur plusieurs navigateurs et internet fixe et 4G et même problème

**Comment by tthma** [comment]
Arf moi non plus ça marchais pas j'avais une erreur 404 à voir demain si ça change quelque chose 
On se contacte demain

**Comment by tthma** [comment]
Aujourd'hui ça ne marche toujours pas.
Erreur 404 encore.
Sur le plugin des tokens le propriétaire parle d'un changement d'api d'enedis bientôt.

Je pense qu'il va falloir repenser bientôt le code pour que ça re fonctionne à nouveau
