### ISSUE TITLE
Aucune donnée dans EVE 

### ISSUE THREAD

**Issue by McSon2** [tthma/homebridge-linky-enedis-meter#17]
Le plugin a l’air de fonctionner, je n’ai pas d’erreur dans la console mais je n’ai aucune donnée dans EVE, pourtant si je teste directement sur conso.boris.sh j’ai bien les données. Faut il attendre pour que les données remonte dans EVE ou ça doit être instantané ?
![IMG_1293](https://github.com/tthma/homebridge-linky-enedis-meter/assets/40039615/6893955a-18d9-4040-b8fc-c35d3b651e46)
![IMG_1294](https://github.com/tthma/homebridge-linky-enedis-meter/assets/40039615/88fdbf70-69d3-4e7f-ad2f-067389fec827)

**Comment by tthma** [comment]
Bonjour 
L'intervalle par défaut est de une heure avant chaque query.
Avez vous d'autre ligne Energy Meter dans vos log qui indique qu'il se passe quelque chose ?
De manière générale vous n'aurez jamais la consommation instantanée l'api enedis a toujours un jour de décalage
