### ISSUE TITLE
Error: Invalid request: The start date must be greater than the history deadline.

### ISSUE THREAD

**Issue by FRame34** [tthma/homebridge-linky-enedis-meter#2]
Hi,

Error in log :
`Error: Invalid request: The start date must be greater than the history deadline.
`

My config :
`        {
            "name": "Garage Linky",
            "usagePointId": " ... ",
            "accessToken": " ... ",
            "refreshToken": " ... ",
            "firstDateRecord": "2020-01-01",
            "update_interval": 60000,
            "accessory": "EnergyMeter"
        }
`

**Comment by tthma** [comment]
Bonjour
il ne faut pas que la première date de donnée soit inferieur à la date de début de réception des données EDF/ENEDIS.
si vous la connaissez pas faut allez sur enedis/edf et regardé à quel période ils ont commencé a récolté les données.

de plus la date ne doit pas être supperieur à un an. (normalement le plugin detecte si ca fait plus d'un an et raccourcis a la date du jours - 365 jours).

deux chemins à vérifier.

J'ai encore quelque galère sur l'historique EVE qui multplie les données je ne sais pas encore pourquoi mais je bosse dessus une prochaine version ne devrait pas tarder à arriver (si j'ai 5min à moi).

**Comment by jgillet** [comment]
J’ai eu le même souci, quelle que soit la date qu’on rentre, même celle de la veille, ça râle.
En fait il faut aller dans l’app Eve et faire un reset. Et hop, ça marche.

**Comment by Libar19** [comment]
Bonjour, J'ai essayé vos 2 solutions et j'ai toujours le meme probleme, parcontre dans Homebridge j'ai ceci:

[10/29/2022, 9:12:28 PM] [Linky Meter] Query start = 1970-01-01 End = 1970-01-08
[10/29/2022, 9:12:29 PM] [Linky Meter] Error: Invalid request: The start date must be greater than the history deadline.
    at /usr/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

pourquoi j'ai une date de 1970 ? je pense que mon probleme vient de là.

**Comment by FRame34** [comment]
Idem, j'ai pas trouvé de solution à ce stade.

**Comment by Libar19** [comment]
J’ai reussi a passer l’erreur en mettant la date a ce format « 2022-10-28T01:30Z ». Et a chaque reset de eve sa fonctionner

maintenant sa ne fonctionne plus. J’ai cette erreur. 

Error: Invalid request The and date parameter must be earlier than the current date.

**Comment by tthma** [comment]
> J’ai reussi a passer l’erreur en mettant la date a ce format « 2022-10-28T01:30Z ». Et a chaque reset de eve sa fonctionner
> 
> 
> 
> maintenant sa ne fonctionne plus. J’ai cette erreur. 
> 
> 
> 
> Error: Invalid request The and date parameter must be earlier than the current date.

Bonjour

Quelle date apparaît dans homebridge ?

A la ligne "Query=" juste avant que l'erreur ne survienne.

Ça va m'aider dans pour trouver d'où viens le bug.
Je regarderai lundi pour déployer une nouvelle version si je trouve d'où ça viens.

Avez vous redémarré homebridge après le reset eve ?

**Comment by Libar19** [comment]
J'ai ceci: [
10/30/2022, 12:37:00 AM] [Linky Meter] Query start = 2022-10-28 End = 2022-10-30
[10/30/2022, 12:37:01 AM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /usr/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

si je modifie la première date dans les réglages sa ne modifie pas la date du "query start".
sa a marché une seul fois quand j'ai fais reset eve sans redémarré homebridge (si je le redémarre sa ne marche pas)

**Comment by tthma** [comment]
> Idem, j'ai pas trouvé de solution à ce stade.

pouvez vous m'écrire la config du plugin ? (en cachant les données sensible).

**Comment by FRame34** [comment]
C'était dans le premier post :

        {
            "name": "Garage Linky",
            "usagePointId": "XXX",
            "accessToken": "XXX",
            "refreshToken": "XXX",
            "firstDateRecord": "2022-06-24",
            "update_interval": 60000,
            "accessory": "EnergyMeter"
        }

J'ai esayé plusieurs formats de date : AAAA-MM-JJ JJ/MM/AAAA JJ-MM-AAAA AAAA/MM/JJ sans succès, toujours cette erreur dans le logs :

[10/31/2022, 8:38:04 AM] [Garage Linky] Query start = 1970-01-01 End = 1970-01-08
[10/31/2022, 8:38:04 AM] [Garage Linky] Error: Error from the Enedis API
Code: 429
Response: {
    "error": "Unknown Error",
    "error_description": "Cette erreur ne fait pas partie des erreurs connues. Veuillez contacter le support",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
    at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by tthma** [comment]
> C'était dans le premier post :
> 
> 
> 
>         {
> 
>             "name": "Garage Linky",
> 
>             "usagePointId": "XXX",
> 
>             "accessToken": "XXX",
> 
>             "refreshToken": "XXX",
> 
>             "firstDateRecord": "2022-06-24",
> 
>             "update_interval": 60000,
> 
>             "accessory": "EnergyMeter"
> 
>         }
> 
> 
> 
> J'ai esayé plusieurs formats de date : AAAA-MM-JJ JJ/MM/AAAA JJ-MM-AAAA AAAA/MM/JJ sans succès, toujours cette erreur dans le logs :
> 
> 
> 
> [10/31/2022, 8:38:04 AM] [Garage Linky] Query start = 1970-01-01 End = 1970-01-08
> 
> [10/31/2022, 8:38:04 AM] [Garage Linky] Error: Error from the Enedis API
> 
> Code: 429
> 
> Response: {
> 
>     "error": "Unknown Error",
> 
>     "error_description": "Cette erreur ne fait pas partie des erreurs connues. Veuillez contacter le support",
> 
>     "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
> 
> }
> 
>     at /homebridge/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:23
> 
>     at runMicrotasks (<anonymous>)
> 
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Avec la mise à jour que je viens d'upload c'est pareil ?(1.1.35)

L'erreur 429 ça c'est enedis ça me le fait des fois mais après quelque essaies quand je laisse tourné ça passe.(bon là 1970 je doute que ça passe au final)

Normalement dans la config du plugin dans l'ui homebridge y a un date picker qui permet de mettre une date au bon format directement. En sélectionnant une date dans un calendrier.

**Comment by Libar19** [comment]
> > Idem, j'ai pas trouvé de solution à ce stade.
> 
> pouvez vous m'écrire la config du plugin ? (en cachant les données sensible).

Reinitialise les valeurs dans eve app pour que la date se modifie sur les logs de homebridge
