### ISSUE TITLE
Error: Invalid request: The end date parameter must be earlier than the current date.

### ISSUE THREAD

**Issue by Libar19** [tthma/homebridge-linky-enedis-meter#3]
Bonjour, le plugin fonctionne sa remonte bien sur EVE app , mais a partir du jour suivant. j'ai ce defaut qui apparait

"[10/31/2022, 12:23:33 AM] [Linky Meter] Query start = 2022-10-28 End = 2022-10-31
[10/31/2022, 12:23:34 AM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at /usr/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5)"

une idée d'ou viens le problème ? (un reset d'eve ne change rien)

**Comment by tthma** [comment]
> Bonjour, le plugin fonctionne sa remonte bien sur EVE app , mais a partir du jour suivant. j'ai ce defaut qui apparait
> 
> "[10/31/2022, 12:23:33 AM] [Linky Meter] Query start = 2022-10-28 End = 2022-10-31 [10/31/2022, 12:23:34 AM] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date. at /usr/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:64:27 at processTicksAndRejections (node:internal/process/task_queues:95:5)"
> 
> une idée d'ou viens le problème ? (un reset d'eve ne change rien)

Mise à jour vers *.35 
normalement le bug est corrigé.

**Comment by Libar19** [comment]
d'accord merci , Le " query start" doit se lancer tout les combien de temps ?

**Comment by tthma** [comment]
> d'accord merci , Le " query start" doit se lancer tout les combien de temps ?

60000 ms par défaut (1minute)

Cependant si les données d'hier sont déjà dans l'historique ça se lancera pas aujourd'hui.

Enedis ne fait pas de l'instantané c'est tjr les données de la veille c'est pour cela que si on met la date du jour il est pas content.

**Comment by Libar19** [comment]
D'accord, après mise a jour sa fonctionne pour le moment mais j'ai eu l'erreur 429 plusieurs fois

**Comment by tthma** [comment]
> D'accord, après mise a jour sa fonctionne pour le moment mais j'ai eu l'erreur 429 plusieurs fois

"Number of authorized requests exceeded" 

Selon la doc api Enedis.

Trop d'appel en peu de temps je dirait.

Si ça gêne vraiment je pourrait faire un gestionnaire d'erreur qui augmente le temps d'appel à l'api à chaque "429" 

Je gère pas les erreurs à l'heure actuel je renvoie juste tel quel les erreurs renvoyé par Enedis

**Comment by Libar19** [comment]
d'accord merci , super le plugin en tous cas merci

**Comment by Libar19** [comment]
Salut, après 24h de fonctionnement voici le problème. le query start ne se lance qu'après avoir réinitialiser les valeur dans eve app et redémarrer homebridge. ne doit t'il pas le faire automatiquement ?

**Comment by tthma** [comment]
> Salut, après 24h de fonctionnement voici le problème. le query start ne se lance qu'après avoir réinitialiser les valeur dans eve app et redémarrer homebridge. ne doit t'il pas le faire automatiquement ?

Si c'est sensé se mettre à jour chaque jour.

Quelle était les dates de query lors du reset ?

Les dates dans le query ont t'elle pris en compte le delta jours depuis le dernier lancement ?

La seul chose qui bloque le lancement de la query c'est que end date est égale à la date du jour-1 ou qu'un reset à été demandé (en attente reset hoebridge) et pour finir une erreur de lecture écriture empêchant l'historique d'être chargé en mémoire.

Normalement un restart homebridge suffit à recharger l'historique en mémoire.

A tester maintenant que la query c'est lancé attendre demain pour voir si ça refais le problème ou si juste hier il attendait un reset pour je ne sais quelle raison.

Nb: je galère à débuger chez moi bouygue me bloque l'accès au site enedis donc je débug en partage de connexion avec mon tél.Donc faire un test sur plusieurs jours est compliqué en partage je suis pas tout le temps à côté de mon rasbery.

Si ça remerde je rajouterai des logs en debug demain et upload une nouvelle version pour creuser d'où viens le problème. 

Je vais lancer le plugin sur mon pc ce soir et le laisser tourner jusqu'au lendemain pour voir

**Comment by Libar19** [comment]
je suis actuellement avec ce query la: "Query start = 2022-10-24 End = 2022-10-31 " sur enedis j'ai bien des donnée pour hier , mais elle ne se transfere pas automatiquement a eve app pour arriver a lancer un "query start" il faut que je reinitialise eve et homebridge.

la je viens de tout reset "[11/1/2022, 9:48:14 AM] [Linky Meter] Query start = 2022-10-24 End = 2022-10-31"

j'attend le finish sa devrait etre bon mais obliger de refaire l'operation demain a mon avis

**Comment by tthma** [comment]
> je suis actuellement avec ce query la: "Query start = 2022-10-24 End = 2022-10-31 " sur enedis j'ai bien des donnée pour hier , mais elle ne se transfere pas automatiquement a eve app pour arriver a lancer un "query start" il faut que je reinitialise eve et homebridge.
> 
> 
> 
> la je viens de tout reset "[11/1/2022, 9:48:14 AM] [Linky Meter] Query start = 2022-10-24 End = 2022-10-31"
> 
> 
> 
> j'attend le finish sa devrait etre bon mais obliger de refaire l'operation demain a mon avis

Ok je crois comprendre ce qui se passe.
Pour faciliter les comparaisons de date je met les heures à 00h00.
Mais là à mon avis il attend 00h00 d'aujourd'hui pour mettre à jour les données d'hier donc au final on a plus 1 jour de décalage mais 2.

Je test ce soir et laisse tourner sur 2 jours je corrigerai dans la foulée si c'est ça.

En gros vous auriez laissé tourné jusqu'à ce soir minuit il se serait mis à jour tous seul.Mais bon ça fait long à attendre.

**Comment by Libar19** [comment]
Ah donc si je met l'heure a la meme heure que la mise a jour d'enedis sa devrait etre bon ?

**Comment by Libar19** [comment]
Ah donc si je met l'heure a la meme heure que la mise a jour d'enedis sa devrait etre bon ?

**Comment by tthma** [comment]
> Ah donc si je met l'heure a la meme heure que la mise a jour d'enedis sa devrait etre bon ?

Non parce que je ne prend pas en compte l'heure je set à 00h00.

Je vais voir demain pour faire une update et faire un test.

J'ouvre une nouvelle issue et clos celle ci
