### ISSUE TITLE
problème mise a jour le lendemain

### ISSUE THREAD

**Issue by tthma** [tthma/homebridge-linky-enedis-meter#5]
> je suis actuellement avec ce query la: "Query start = 2022-10-24 End = 2022-10-31 " sur enedis j'ai bien des donnée pour hier , mais elle ne se transfere pas automatiquement a eve app pour arriver a lancer un "query start" il faut que je reinitialise eve et homebridge.
> 
> 
> 
> la je viens de tout reset "[11/1/2022, 9:48:14 AM] [Linky Meter] Query start = 2022-10-24 End = 2022-10-31"
> 
> 
> 
> j'attend le finish sa devrait etre bon mais obliger de refaire l'operation demain a mon avis

Ok je crois comprendre ce qui se passe.
Pour faciliter les comparaisons de date je met les heures à 00h00.
Mais là à mon avis il attend 00h00 d'aujourd'hui pour mettre à jour les données d'hier donc au final on a plus 1 jour de décalage mais 2.

Je test ce soir et laisse tourner sur 2 jours je corrigerai dans la foulée si c'est ça.

En gros vous auriez laissé tourné jusqu'à ce soir minuit il se serait mis à jour tous seul.Mais bon ça fait long à attendre.

__Originally posted by @tthma in https://github.com/tthma/homebridge-linky-enedis-meter/issues/3#issuecomment-1298272196__

**Comment by Libar19** [comment]
Merci pour la mise a jour. Aujourd'hui tout a fonctionné pour moi. Je tiens au jus d'ici demain

**Comment by tthma** [comment]
Content que ca fonctionne !

j'ai laissé tourné toute la nuit j'ai eu quelque erreur tout de même.

> [04/11/2022, 00:00:39] [Linky Meter] Error: Invalid request: The end date parameter must be earlier than the current date.
    at homebridge-linky-enedis-meter\node_modules\linky\dist\src\index.js:64:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
de 00:00:39 => 01:00:03.

et ensuite plus tard dans la nuit

> [04/11/2022, 01:00:08] [Linky Meter] Error: Error from the Enedis API
Code: 404
Response: {
    "error": "no_data_found",
    "error_description": "no measure found for this usage point",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
    at homebridge-linky-enedis-meter\node_modules\linky\dist\src\index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

même erreur jusqu'à 03:12:30.

donc premier point la demande de requête ne doit pas avoisiner les 00:00 le module Linky n'apprécie pas (première erreur).
et second point les données de télérelève ne sont pas sur ENEDIS avant 03:12:00 Visiblement (seconde erreur).

je vais faire une Mise à jour pour bloquer les Querry jusqu'a 05:00 du matin ca laissera le temps au données d'arriver sur ENEDIS. (Et perso je regarde pas ma conso à 5h du mat).

**Comment by tthma** [comment]
> Alors faux espoir sa ne fonctionne pas automatiquement :/. Il est 10h et je n'est toujours le query start qui c'est lancé. J'ai bien les donnee sur l'applis enedis mais pas sur eve :/

Avez vous la dernière version ?
Y a quoi dans les logs vers 5h du mat ?

Vous faites tourner sur quel machine un pc un raspberry ?

**Comment by tthma** [comment]
> Alors faux espoir sa ne fonctionne pas automatiquement :/. Il est 10h et je n'est toujours le query start qui c'est lancé. J'ai bien les donnee sur l'applis enedis mais pas sur eve :/

Le message est dans "in the futur" 😂
A 10:57 ??? Il est 10:14.

**Comment by Libar19** [comment]
Alors faux espoir sa ne fonctionne pas automatiquement :/. Il est 10h et je n'est toujours le query start qui c'est lancé. J'ai bien les donnee sur l'applis enedis mais pas sur eve :/

**Comment by Libar19** [comment]
Sur un Orange-pizero

**Comment by tthma** [comment]
> Sur un Orange-pizero

Ok du coup pour la dernière version ?
*.38

Et les logs de 5h du mat ?

**Comment by Libar19** [comment]
Justement. Il n'y en a pas 😅

**Comment by tthma** [comment]
> Justement. Il n'y en a pas 😅

C'est la dernière version du plugin ?

Même plusieurs jours passé pas de log de query ?

**Comment by Libar19** [comment]
Je suis obliger de reset eve a chaque fois. Sa fais 2 jours pour le moment. Je controle encore demain et je te fais un retour

**Comment by Libar19** [comment]
Problème resolu tout fonctionne bien 👌🏼

**Comment by tthma** [comment]
Allez ca part sur un Résolu !

Merci du retour.

Perso j'attend tjr que bouygue me débloque le site Enedis pour pouvoir utiliser mon propre plugin !!!!
