### ISSUE TITLE
Données manquantes

### ISSUE THREAD

**Issue by jgillet** [tthma/homebridge-linky-enedis-meter#6]
Hello,
Parfois on ne récupère pas les données, on a des trous dans les graphs (ex : aucune donnée pendant 12 heures, avant-hier, mon homebridge était en rade...), comment fait-on pour compléter / récupérer sans devoir tout ré-initialiser ?
Merci

**Comment by tthma** [comment]
Salut 

la solution qui me viens à l'esprit tout de suite est un peu tricky mais ca fonctionne.

il faut chercher dans les fichiers de homebridge.
il y a un fichier Json "energymeter."uuid".json".
il à cette structure.
{
	"fsfirstToken": "***",
	"fsfirstrefreshtoken": "***",
	"fstoken": "***",
	"fsrefreshtoken": "***",
	"firstdate": "2022-11-06T23:00:00.000Z",
	"uploadEntry": 1,
	"total": 294.73899999999977
}
il faut changer la date sur "firsdate" et ca va repartir à la date enregistré dans ce champs.
attention il faut bien supprimer les mesures dans eve sinon ca vas faire doublons.(de la date "firstdate" à la date du jour).

Au besoin je peut peut etre rajouter un champs dans le fichier config dans homebridge si cela est nécessaire.

Dite moi je ferai une mise à jour au besoin dès que j'aurai 5min.

**Comment by jgillet** [comment]
J'ai effacé mes données dans Eve à partir du 9 novembre minuit, modifié "firstdate":"2022-11-09T00:00:00.000Z"
et attendu, et c'est passé ;) Merci ! 
En revanche, effectivement, s'il y avait un moyen de récupérer qu'un seul jour en particulier comme en ligne de commande, ce serait top, mais bon, ce n'est pas urgent du tout :D

**Comment by jgillet** [comment]
en revanche, depuis... ça plante Homebridge

```
Nov 15 07:35:09 daemon[19460]: [11/15/2022, 7:35:09 AM] [Linky] Query start = 2022-11-14 End = 2022-11-15
Nov 15 07:35:11 daemon[19460]: [11/15/2022, 7:35:11 AM] TypeError: Cannot read properties of null (reading 'time')
Nov 15 07:35:11 daemon[19460]:     at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/index.js:462:78
Nov 15 07:35:11 daemon[19460]:     at Array.find (<anonymous>)
Nov 15 07:35:11 daemon[19460]:     at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/index.js:462:52
Nov 15 07:35:11 daemon[19460]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Nov 15 07:35:11 daemon[19460]: [11/15/2022, 7:35:11 AM] Got SIGTERM, shutting down Homebridge...
Nov 15 07:35:11 daemon[19460]: [11/15/2022, 7:35:11 AM] Got SIGTERM, shutting down child bridge process...
```

J'avais relancé Homebridge ce matin à 7h25 suite au précédent plantage à 6h09, il ne s'est rien passé de particulier la nuit depuis la veille (le 14 donc, où j'ai tout récup depuis le 9/11) :

```
Nov 15 06:09:44 daemon[12707]: [11/15/2022, 6:09:44 AM] [Linky] Query start = 2022-11-14 End = 2022-11-15
Nov 15 06:09:46 daemon[12707]: refreshtoken
Nov 15 06:09:48 daemon[12707]: [11/15/2022, 6:09:48 AM] TypeError: Cannot read properties of undefined (reading 'time')
Nov 15 06:09:48 daemon[12707]:     at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/index.js:462:78
Nov 15 06:09:48 daemon[12707]:     at Array.find (<anonymous>)
Nov 15 06:09:48 daemon[12707]:     at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/index.js:462:52
Nov 15 06:09:48 daemon[12707]:     at runMicrotasks (<anonymous>)
Nov 15 06:09:48 daemon[12707]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Nov 15 06:09:48 daemon[12707]: [11/15/2022, 6:09:48 AM] Got SIGTERM, shutting down Homebridge...
Nov 15 06:09:48 daemon[12707]: [11/15/2022, 6:09:48 AM] Got SIGTERM, shutting down child bridge process...
```

**Comment by tthma** [comment]
Bjr 

Je corrige et je déploie une nouvelle version.

**Comment by tthma** [comment]
Mise à jour efféctué

**Comment by jgillet** [comment]
Nickel, ça fonctionne ! Merci beaucoup !
