### ISSUE TITLE
Problème de remontée de données

### ISSUE THREAD

**Issue by leauhiic** [tthma/homebridge-linky-enedis-meter#7]
Bonjour,
Juste après l'installation, les requetes reviennents avec des erreurs :
`[14/11/2022, 16:20:14] [Linky] Query start = 2020-01-01 End = 2020-01-08

[14/11/2022, 16:20:15] [Linky] Error: Invalid request: The start date must be greater than the history deadline.
    at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:66:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)` 

J'ai pourtant bien mis le 15/11/2021 dans le fichier de configuration.

Merci pour votre aide.

**Comment by tthma** [comment]
Bonjour 
Pourrai je avoir un extrait du fichier configuration concernant le plugin.
En prenant soin de cacher les données sensible

**Comment by leauhiic** [comment]
`{
            "name": "Linky",
            "usagePointId": "xxxxxxxx",
            "accessToken": "xxxxxxxx",
            "refreshToken": "xxxxxxx",
            "firstDateRecord": "2021-11-15T00:00:00Z",
            "update_interval": 60000,
            "accessory": "EnergyMeter"
}`

**Comment by tthma** [comment]
Bizzare ça me paraît correct comme saisie.
Essayez de faire un reset dans l'application Ève voir si ça repart.
A défaut je verrai demain pour trouver la cause du pourquoi du comment

**Comment by leauhiic** [comment]
Comment faire le reset dans Eve ?
Merci pour le coup de main.

**Comment by leauhiic** [comment]
Toutes les minutes, j'ai une requête qui part avec le Query Start = 2020-01-01 End = 2020-01-08 dans les logs de Homebridge. 
Et donc toujours la même erreur.

**Comment by tthma** [comment]
> Toutes les minutes, j'ai une requête qui part avec le Query Start = 2020-01-01 End = 2020-01-08 dans les logs de Homebridge. Et donc toujours la même erreur.

Donc je suppose que vous avez trouvé le moyen de reset eve ?

Rien à voir mes toute les minutes c'est bcp vaux mieux augmenter le temps entre les requêtes. 

Une fois le reset eve effectué faut restart homebridge.
![eve](https://user-images.githubusercontent.com/113852575/201899778-92b081cd-202f-4664-985c-0a3e4ce37adf.jpg)

Tenez moi au courant

**Comment by leauhiic** [comment]
J'ai modifié le temps à 10minutes, reseté dans Eve et relancé Homebridge, toujours le même problème.

**Comment by leauhiic** [comment]
Après plusieurs reset, j'ai un nouveau message d'erreur : 
`[15/11/2022, 14:00:03] [Linky] Query start = 2021-11-16 End = 2021-11-23
[15/11/2022, 14:00:09] [Linky] Error: Error from the Enedis API
Code: 500
Response: {
    "error": "Internal Server error",
    "error_description": "Un problème a été rencontré lors du traitement.",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
    at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:68:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

[15/11/2022, 14:00:09] [Linky] Error: Error from the Enedis API
Code: 500
Response: {
    "error": "Internal Server error",
    "error_description": "Un problème a été rencontré lors du traitement.",
    "error_uri": "https://bluecoder.enedis.fr/api-doc/consulter-souscrire"
}
    at /usr/local/lib/node_modules/homebridge-linky-enedis-meter/node_modules/linky/dist/src/index.js:68:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by leauhiic** [comment]
Après plusieurs tentative de connexion, les données sont bien rappatriées.

**Comment by tthma** [comment]
> Après plusieurs tentative de connexion, les données sont bien rappatriées.

Mdr j'ai rien fait j'ai même pas eu le temps de regarder aujourd'hui.

Erreur 500 ça viens d'enedis et de leur serveur.

Attention à pas call trop souvent l'api genre toute les minutes ils vont pas aimer et balancer des erreur 429 etc etc 

Tant mieux que ça fonctionne dorénavant.

Faut quand même que je regarde parceque cette erreur est récurrente pour le premier lancement
