### ISSUE TITLE
Error on reset Eve entries

### ISSUE THREAD

**Issue by Hydrog3n** [tthma/homebridge-linky-enedis-meter#8]
Bonjour, 

Merci pour ce plugin qui est top. J'ai pourtant un soucis je n'arrive plus a sync les données j'ai essayé de reset les données depuis l'app eve mais dans homebridge j'ai cette erreur. 

```
[12/3/2022, 6:29:07 PM] [Linky Meter] Reset Detected From EVE App must Restart HomeBridge
[12/3/2022, 6:29:07 PM] [homebridge-linky-enedis-meter] This plugin threw an error from the characteristic 'Time from totalizer reset': Unhandled error thrown inside write handler for characteristic: ENOENT: no such file or directory, unlink '/var/lib/homebridge/xxxxxxxxxxx.json'. See https://homebridge.io/w/JtMGR for more info.
```
Quelqu'un a plus d'information sur ce que je peux faire. 

Merci

**Comment by tthma** [comment]
> Bonjour, 
> 
> 
> 
> Merci pour ce plugin qui est top. J'ai pourtant un soucis je n'arrive plus a sync les données j'ai essayé de reset les données depuis l'app eve mais dans homebridge j'ai cette erreur. 
> 
> 
> 
> ```
> 
> [12/3/2022, 6:29:07 PM] [Linky Meter] Reset Detected From EVE App must Restart HomeBridge
> 
> [12/3/2022, 6:29:07 PM] [homebridge-linky-enedis-meter] This plugin threw an error from the characteristic 'Time from totalizer reset': Unhandled error thrown inside write handler for characteristic: ENOENT: no such file or directory, unlink '/var/lib/homebridge/xxxxxxxxxxx.json'. See https://homebridge.io/w/JtMGR for more info.
> 
> ```
> 
> Quelqu'un a plus d'information sur ce que je peux faire. 
> 
> 
> 
> Merci
> 
> 

J'ai édité le nom du fichier c'est le numéro de pl et les gens n'ont pas à savoir.
C'est arrivé du jour au lendemain ? Suite à un crash de homebridge ou d'un reset ?
En gros il dit qu'il trouve pas le fichier json de config du plugin ce qui est étrange.
Normalement il disparaît pas comme ca.

Si je peux avoir plus d'info ?

**Comment by Hydrog3n** [comment]
Ah merci bien vu, 

Non je suis en train de le configuré depuis aujourd'hui,  j'ai de la data de janvier puis je me suis dit c'est peut être un peu lointains donc j'ai voulu reduire et j'ai mit debut novembre. 

Je vais rien toucher et attendre jusqu'a demain on verra si il y a plus ou non.

**Comment by tthma** [comment]
> Ah merci bien vu, 
> 
> 
> 
> Non je suis en train de le configuré depuis aujourd'hui,  j'ai de la data de janvier puis je me suis dit c'est peut être un peu lointains donc j'ai voulu reduire et j'ai mit debut novembre. 
> 
> 
> 
> Je vais rien toucher et attendre jusqu'a demain on verra si il y a plus ou non. 

Faut voir si dans les logs y a une erreur ou si il fait des query.

Sinon désinstaller le plugin et le réinstaller peut être.
Me faudrait plus d'info pour que je puisse essayer lundi sur mon ordinateur et reproduire le même problème

**Comment by Hydrog3n** [comment]
Ok je viens d'aller voir j'ai de la data qui remonte ça c'est top mais j'ai maintenant en boucle : 

```
[12/3/2022, 7:06:20 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
```

**Comment by tthma** [comment]
> Ok je viens d'aller voir j'ai de la data qui remonte ça c'est top mais j'ai maintenant en boucle : 
> 
> 
> 
> ```
> 
> [12/3/2022, 7:06:20 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> ```

En fait quand on va chercher de la data loin dans le temps pour éviter la perte de donnée y a que 4000 de mémoire pour pas faire crash homebridge.
Donc je bloque quand la mémoire est saturé jusqu'à ce que l'utilisateur rafraîchisse son Ève et que les données s'enregistre dans Ève.
Après ça raz la mémoire et ça repart de plus belle.

**Comment by Hydrog3n** [comment]
D'accord sauf que dans mon cas j'ai bien toute les données d'enregistrer dans l'app. Je vais faire in reset on va voir si c'est mieux

**Comment by Hydrog3n** [comment]
Après plusieurs test j'ai reset tout le module et supprimer toute mes donéees. J'ai l'impression que quand le transfere sur l'app est fait les données ne sont pas bien "flush" de la memoire car j'ai en bloucle que les données doivent être flush
 

```
[12/4/2022, 1:52:21 PM] [Linky Meter] Query start = 2022-11-08 End = 2022-11-15
[12/4/2022, 1:52:26 PM] [Linky Meter] Query 2022-11-08/2022-11-15 Finish
[12/4/2022, 1:53:21 PM] [Linky Meter] Query start = 2022-11-15 End = 2022-11-22
[12/4/2022, 1:53:30 PM] [Linky Meter] Query 2022-11-15/2022-11-22 Finish
[12/4/2022, 1:54:21 PM] [Linky Meter] Transfer to Eve App Finish
[12/4/2022, 1:55:21 PM] [Linky Meter] Query start = 2022-11-22 End = 2022-11-29
[12/4/2022, 1:55:29 PM] [Linky Meter] Query 2022-11-22/2022-11-29 Finish
[12/4/2022, 1:56:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
[12/4/2022, 1:57:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
[12/4/2022, 1:58:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
[12/4/2022, 1:59:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
[12/4/2022, 2:00:21 PM] [Linky Meter] Transfer to Eve App Finish
[12/4/2022, 2:01:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
```

**Comment by tthma** [comment]
> Après plusieurs test j'ai reset tout le module et supprimer toute mes donéees. J'ai l'impression que quand le transfere sur l'app est fait les données ne sont pas bien "flush" de la memoire car j'ai en bloucle que les données doivent être flush
> 
>  
> 
> 
> 
> ```
> 
> [12/4/2022, 1:52:21 PM] [Linky Meter] Query start = 2022-11-08 End = 2022-11-15
> 
> [12/4/2022, 1:52:26 PM] [Linky Meter] Query 2022-11-08/2022-11-15 Finish
> 
> [12/4/2022, 1:53:21 PM] [Linky Meter] Query start = 2022-11-15 End = 2022-11-22
> 
> [12/4/2022, 1:53:30 PM] [Linky Meter] Query 2022-11-15/2022-11-22 Finish
> 
> [12/4/2022, 1:54:21 PM] [Linky Meter] Transfer to Eve App Finish
> 
> [12/4/2022, 1:55:21 PM] [Linky Meter] Query start = 2022-11-22 End = 2022-11-29
> 
> [12/4/2022, 1:55:29 PM] [Linky Meter] Query 2022-11-22/2022-11-29 Finish
> 
> [12/4/2022, 1:56:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> [12/4/2022, 1:57:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> [12/4/2022, 1:58:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> [12/4/2022, 1:59:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> [12/4/2022, 2:00:21 PM] [Linky Meter] Transfer to Eve App Finish
> 
> [12/4/2022, 2:01:21 PM] [Linky Meter] Persit Memory Full Please push data to Eve App (Refresh) For Prevent lost Data History
> 
> ```

En slidant de haut en bas sur la page des courbes des mesures aussi ?

![image](https://user-images.githubusercontent.com/113852575/205492289-43c353e1-1a31-4ca8-9b63-ab9573879733.png)

Bon la c'est des températures mais le principe est le même

**Comment by Hydrog3n** [comment]
Oui j'ai bien les mesures dans l'app

**Comment by tthma** [comment]
Normalement je capte le moment où on slide de haut en bas pour reset le message.

Sinon je checkerai lundi si vous avez accès aux fichier de homebrige je veux bien votre fichier json en cachant les token et le numéro de pl

**Comment by Hydrog3n** [comment]
Hello, 
ça semble bon ajd, J'ai eu un reboot de homebridge ça semble l'avoir débloqué. On peut close mais je pense que quand on demande des dates bien trop loin ça a du mal parfois

**Comment by tthma** [comment]
> Hello, 
> 
> ça semble bon ajd, J'ai eu un reboot de homebridge ça semble l'avoir débloqué. On peut close mais je pense que quand on demande des dates bien trop loin ça a du mal parfois

Ok je vais attendre un peu quand même.
J'ai déjà fais des tests sur plus d'un an j'ai pas eu de soucis.
J'ai fais le choix de bloqué l'export des données quand le cache est plein pour éviter la perte de data.
Après je peux peut être ajouter une option pour ceux que ça n'intéresse pas.

**Comment by Hydrog3n** [comment]
D'accord, je peux essayer a nouveau de reprendre depuis le 01/01/2022 mais j'ai eu quelque crash memoire (Heap memory full) 

Oui c'est un bon choix c'est plus que ça donne l'impression de pas se vider correctement quand on rentre dans la condition eve app transfered. 

J'ai un peu lu le code mais connaissant pas trop fakegato pas simple d'aller plus loin. 

On pourrais rajouter une option de debug pour avoir plus d'info quand cette fonction est activer mais pas sur que d'etre utile pour le moment.
